"""Astar Island local tooling package."""

from .archetypes import (
    ArchetypeReport,
    ClusteringResult,
    ClusterPoint,
    COMPACT_FEATURES,
    DEFAULT_FEATURES,
    DYNAMICS_FEATURES,
    RoundFingerprint,
    SeedFingerprint,
    build_archetype_report,
    cluster_round_fingerprints,
    compute_round_fingerprints,
)
from .baseline_b import (
    BaselineBConfig,
    BaselineBReport,
    LogisticRegressionModel,
    RoundBaselineResult,
    SeedBaselineResult,
    build_seed_feature_grid,
    evaluate_baseline_b_leave_one_round_out,
    predict_with_model,
    train_multinomial_logistic_regression,
)
from .baseline_c import (
    BaselineCConfig,
    BaselineCReport,
    RoundSpatialResult,
    SeedSpatialResult,
    SpatialSoftmaxModel,
    build_seed_spatial_feature_grid,
    evaluate_baseline_c_leave_one_round_out,
    predict_with_spatial_model,
    spatial_feature_names,
    train_spatial_softmax_model,
)
from .importance import (
    ImportanceConfig,
    dynamic_importance_map_from_initial_state,
    dynamic_importance_maps_for_round,
)
from .offline_emulator import (
    OfflineRoundResult,
    OfflineRoundState,
    SeedEvaluation,
    ViewportObservation,
    ViewportQuery,
    run_offline_round,
)
from .parsing import load_json, parse_analysis_seed, parse_round_detail, parse_round_score
from .priors import (
    PriorConfig,
    baseline_prior_for_round,
    baseline_prior_from_initial_grid,
    dynamic_importance_from_prior,
)
from .query_policy import (
    DeterministicThreePhasePolicyConfig,
    DeterministicThreePhaseQueryPolicy,
)
from .round_data import (
    LeaveOneRoundOutSplit,
    RoundRecord,
    RoundSeedRecord,
    leave_one_round_out_splits,
    load_leave_one_round_out,
    load_round_dataset,
)
from .round_latent import (
    RoundLatentConditionalModel,
    RoundLatentConfig,
    RoundLatentEncoder,
    RoundLatentVector,
)
from .scoring import score_round, score_seed, weighted_kl
from .submission import (
    SeedSubmissionPlan,
    build_safe_round_submission,
    floor_and_normalize,
    missing_seed_indices,
    serialize_submission,
    validate_prediction_tensor,
)

__all__ = [
    "ArchetypeReport",
    "BaselineBConfig",
    "BaselineBReport",
    "BaselineCConfig",
    "BaselineCReport",
    "COMPACT_FEATURES",
    "ClusterPoint",
    "ClusteringResult",
    "DEFAULT_FEATURES",
    "DeterministicThreePhasePolicyConfig",
    "DeterministicThreePhaseQueryPolicy",
    "DYNAMICS_FEATURES",
    "ImportanceConfig",
    "LeaveOneRoundOutSplit",
    "LogisticRegressionModel",
    "OfflineRoundResult",
    "OfflineRoundState",
    "PriorConfig",
    "RoundBaselineResult",
    "RoundSpatialResult",
    "RoundFingerprint",
    "RoundLatentConditionalModel",
    "RoundLatentConfig",
    "RoundLatentEncoder",
    "RoundLatentVector",
    "RoundRecord",
    "RoundSeedRecord",
    "SeedSubmissionPlan",
    "SeedBaselineResult",
    "SeedEvaluation",
    "SeedSpatialResult",
    "SeedFingerprint",
    "SpatialSoftmaxModel",
    "ViewportObservation",
    "ViewportQuery",
    "baseline_prior_for_round",
    "baseline_prior_from_initial_grid",
    "build_archetype_report",
    "build_safe_round_submission",
    "build_seed_feature_grid",
    "build_seed_spatial_feature_grid",
    "cluster_round_fingerprints",
    "compute_round_fingerprints",
    "dynamic_importance_from_prior",
    "dynamic_importance_map_from_initial_state",
    "dynamic_importance_maps_for_round",
    "evaluate_baseline_b_leave_one_round_out",
    "evaluate_baseline_c_leave_one_round_out",
    "floor_and_normalize",
    "leave_one_round_out_splits",
    "load_json",
    "load_leave_one_round_out",
    "load_round_dataset",
    "missing_seed_indices",
    "parse_analysis_seed",
    "parse_round_detail",
    "parse_round_score",
    "predict_with_model",
    "predict_with_spatial_model",
    "run_offline_round",
    "score_round",
    "score_seed",
    "serialize_submission",
    "spatial_feature_names",
    "train_multinomial_logistic_regression",
    "train_spatial_softmax_model",
    "validate_prediction_tensor",
    "weighted_kl",
]
